var isDone = false;
console.log(isDone);
var deLiteral = 6;
var hexLiteral = 0xf00d;
var binaryLiteral = 10;
var octalLiteral = 484;
console.log(deLiteral);
console.log(hexLiteral);
console.log(binaryLiteral);
console.log(octalLiteral);
console.log('/n');
var name2 = "bob";
console.log(name2);
name2 = "smith";
console.log(name2);
